# Default initial positions for rover_arm_moveit's ros2_control fake system

initial_positions:
  ee_rotation_joint_x: 0.0
  ee_rotation_joint_y: 0.0
  ee_rotation_joint_z: 0.0
  link1_joint: 0.0
  link2_joint: 0.0
  link3_joint: 0.0
  link4_joint: 0.0