# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - ee_rotation_joint_x
      - ee_rotation_joint_y
      - ee_rotation_joint_z